### ISSUE TITLE
Friendship attribute

### ISSUE THREAD

**Issue by dustin-wright-bbn** [NextCenturyCorporation/itm-evaluation-server#19]
Currently there is no overlap between TA1 ADEPT training scenarios and the evaluation scenario for ADEPT.  This gap is a reason (amongst others) the training data isn't useful for evaluation.
The evaluation scenario's talk about an attribute called Friendship.  The training scenario's talk about Fairness.  Let's consider these two attributes the opposite of one another, which will allow this friendship/fairness concept to be a bridge between training and evaluation.

**Comment by nextcen-dgemoets** [comment]
The kdma attributes (and their values) in the TA3 probe configuration files were made up by TA3 as place-holders for when we learned correct/appropriate attributes and values from TA1.  We'll be happy to update these values in our upcoming release, which includes using actual scenario, probe, and choice IDs from the TA1s.

Please advise if any of the values themselves should be altered beyond `fairness = 10-friendship`.  These values were place-holders.

**Comment by dustin-wright-bbn** [comment]
@nextcen-dgemoets I don't think any other changes required.  PR at https://github.com/NextCenturyCorporation/itm-evaluation-server/pull/20

**Comment by nextcen-dgemoets** [comment]
@dustin-wright-bbn   Just note that this fix isn't currently available in the `main` branch, but is available in the `development` branch.  Once everything else has been reviewed and merged into `development`, the latter will be merged into `main`, which we'll announce.  Thank you!

**Comment by nextcen-dgemoets** [comment]
FYI, this fix is now available in the `main` branch of the repository, via #24 .
