### ISSUE TITLE
Installing with requirements.txt installs connexion 3.0 which is unsupported

### ISSUE THREAD

**Issue by DavidMChan** [NextCenturyCorporation/itm-evaluation-server#36]
Currently, the existing requirements.txt only specifies connexion >= 2.6, but should also specify connexion < 3.0 (since their latest API redesign released on Nov. 2 is unsupported). It also seems like connexion 2.6/2.7 are unsupported due to conflicts in openapi-spec-validator-0.7.1 -- I was able to get this working with connexion 2.14.x.

**Comment by brianpippin** [comment]
Thanks we have added this to our JIRA Board and will try to get a fix out for this soon.
